/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { HTTPClient } from "./http.js";
import { Logger } from "./logger.js";
import { RetryConfig } from "./retries.js";
import { Params, pathToFunc } from "./url.js";

/**
 * A mock server for testing and development purposes
 */
export const ServerMockServer = "Mock Server";
/**
 * The production server for the Train Travel API
 */
export const ServerProduction = "Production";
/**
 * Contains the list of servers available to the SDK
 */
export const ServerList = {
  [ServerMockServer]: "https://try.microcks.io/rest/Train+Travel+API/1.0.0",
  [ServerProduction]: "https://api.example.com",
} as const;

export type SDKOptions = {
  oAuth2?: string | (() => Promise<string>) | undefined;

  httpClient?: HTTPClient;
  /**
   * Allows overriding the default server used by the SDK
   */
  server?: keyof typeof ServerList | undefined;
  /**
   * Allows overriding the default server URL used by the SDK
   */
  serverURL?: string | undefined;
  /**
   * Allows overriding the default user agent used by the SDK
   */
  userAgent?: string | undefined;
  /**
   * Allows overriding the default retry config used by the SDK
   */
  retryConfig?: RetryConfig;
  timeoutMs?: number;
  debugLogger?: Logger;
};

export function serverURLFromOptions(options: SDKOptions): URL | null {
  let serverURL = options.serverURL;

  const params: Params = {};

  if (!serverURL) {
    const server = options.server ?? ServerMockServer;
    serverURL = ServerList[server] || "";
  }

  const u = pathToFunc(serverURL)(params);
  return new URL(u);
}

export const SDK_METADATA = {
  language: "typescript",
  openapiDocVersion: "1.3.0",
  sdkVersion: "0.3.0",
  genVersion: "2.941.0",
  userAgent: "speakeasy-sdk/typescript 0.3.0 2.941.0 1.3.0 train-travel-sdk",
} as const;
