/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Available scopes for the OAuth2 OAuth 2.0 scheme (authorizationCode flow).
 *
 * @remarks
 * OAuth 2.0 following RFC8725 best practices, with Authorization Code
 * and Device Authorization grants.
 */
export type OAuth2Scope =
  /**
   * Read access
   */
  | "read"
  /**
   * Write access
   */
  | "write";
