/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { TrainTravelSDKBookings } from "./traintravelsdkbookings.js";

export class BookingAndPayment extends ClientSDK {
  private _bookings?: TrainTravelSDKBookings;
  get bookings(): TrainTravelSDKBookings {
    return (this._bookings ??= new TrainTravelSDKBookings(this._options));
  }
}
