/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { list, ListAcceptEnum } from "../funcs/list.js";
import {
  queryStations,
  QueryStationsAcceptEnum,
} from "../funcs/queryStations.js";
import { validateWebhook } from "../funcs/validateWebhook.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import * as webhooks from "../models/webhooks/index.js";
import { unwrapAsync } from "../types/fp.js";
import { BookingAndPayment } from "./bookingandpayment.js";
import { Bookings } from "./bookings.js";
import { Search } from "./search.js";

export { ListAcceptEnum } from "../funcs/list.js";

export { QueryStationsAcceptEnum } from "../funcs/queryStations.js";

export class TrainTravelSDK extends ClientSDK {
  private _search?: Search;
  get search(): Search {
    return (this._search ??= new Search(this._options));
  }

  private _bookingAndPayment?: BookingAndPayment;
  get bookingAndPayment(): BookingAndPayment {
    return (this._bookingAndPayment ??= new BookingAndPayment(this._options));
  }

  private _bookings?: Bookings;
  get bookings(): Bookings {
    return (this._bookings ??= new Bookings(this._options));
  }

  /**
   * Get a list of train stations
   *
   * @remarks
   * Returns a paginated and searchable list of all train stations.
   *
   * For complex or sensitive filters, prefer the beta `QUERY /stations` operation,
   * which sends criteria in the request body instead of the URL.
   */
  async list(
    request: operations.GetStationsRequest,
    options?: RequestOptions & { acceptHeaderOverride?: ListAcceptEnum },
  ): Promise<operations.GetStationsResponse> {
    return unwrapAsync(list(
      this,
      request,
      options,
    ));
  }

  /**
   * Query train stations
   *
   * @remarks
   * Returns a paginated and searchable list of train stations.
   *
   * Uses the HTTP [QUERY](https://www.ietf.org/archive/id/draft-ietf-httpbis-safe-method-w-body-08.html)
   * method: filter criteria are sent in the request body (safe and idempotent,
   * like GET, but without putting search terms in the URL).
   */
  async queryStations(
    request: operations.QueryStationsRequest,
    options?: RequestOptions & {
      acceptHeaderOverride?: QueryStationsAcceptEnum;
    },
  ): Promise<operations.QueryStationsResponse> {
    return unwrapAsync(queryStations(
      this,
      request,
      options,
    ));
  }

  async validateWebhook({
    request,
  }: {
    request: {
      body: string;
      headers: Record<string, string> | Headers;
      url: string;
      method: string;
    } | Request;
  }): Promise<webhooks.NewBookingRequestBody> {
    return unwrapAsync(validateWebhook(
      this,
      { request },
    ));
  }
}
