/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { list, ListAcceptEnum } from "../funcs/list.js";
import {
  queryStations,
  QueryStationsAcceptEnum,
} from "../funcs/queryStations.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export { ListAcceptEnum } from "../funcs/list.js";

export { QueryStationsAcceptEnum } from "../funcs/queryStations.js";

export class Stations extends ClientSDK {
  /**
   * Get a list of train stations
   *
   * @remarks
   * Returns a paginated and searchable list of all train stations.
   *
   * For complex or sensitive filters, prefer the beta `QUERY /stations` operation,
   * which sends criteria in the request body instead of the URL.
   */
  async list(
    request: operations.GetStationsRequest,
    options?: RequestOptions & { acceptHeaderOverride?: ListAcceptEnum },
  ): Promise<operations.GetStationsResponse> {
    return unwrapAsync(list(
      this,
      request,
      options,
    ));
  }

  /**
   * Query train stations
   *
   * @remarks
   * Returns a paginated and searchable list of train stations.
   *
   * Uses the HTTP [QUERY](https://www.ietf.org/archive/id/draft-ietf-httpbis-safe-method-w-body-08.html)
   * method: filter criteria are sent in the request body (safe and idempotent,
   * like GET, but without putting search terms in the URL).
   */
  async queryStations(
    request: operations.QueryStationsRequest,
    options?: RequestOptions & {
      acceptHeaderOverride?: QueryStationsAcceptEnum;
    },
  ): Promise<operations.QueryStationsResponse> {
    return unwrapAsync(queryStations(
      this,
      request,
      options,
    ));
  }
}
