/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  bookingPaymentBookingsCreateJson,
  CreateJsonAcceptEnum,
} from "../funcs/bookingPaymentBookingsCreateJson.js";
import {
  bookingPaymentBookingsCreateRaw,
  CreateRawAcceptEnum,
} from "../funcs/bookingPaymentBookingsCreateRaw.js";
import { bookingPaymentBookingsDelete } from "../funcs/bookingPaymentBookingsDelete.js";
import {
  bookingPaymentBookingsGet,
  GetAcceptEnum,
} from "../funcs/bookingPaymentBookingsGet.js";
import {
  bookingPaymentBookingsList,
  ListAcceptEnum,
} from "../funcs/bookingPaymentBookingsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export { ListAcceptEnum } from "../funcs/bookingPaymentBookingsList.js";

export { CreateJsonAcceptEnum } from "../funcs/bookingPaymentBookingsCreateJson.js";

export { CreateRawAcceptEnum } from "../funcs/bookingPaymentBookingsCreateRaw.js";

export { GetAcceptEnum } from "../funcs/bookingPaymentBookingsGet.js";

export class TrainTravelSDKBookings extends ClientSDK {
  /**
   * List existing bookings
   *
   * @remarks
   * Returns a list of all trip bookings by the authenticated user.
   */
  async list(
    request: operations.GetBookingsRequest,
    options?: RequestOptions & { acceptHeaderOverride?: ListAcceptEnum },
  ): Promise<operations.GetBookingsResponse> {
    return unwrapAsync(bookingPaymentBookingsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a booking
   *
   * @remarks
   * A booking is a temporary hold on a trip. It is not confirmed until the payment is processed.
   */
  async createJson(
    request: components.BookingInput,
    options?: RequestOptions & { acceptHeaderOverride?: CreateJsonAcceptEnum },
  ): Promise<operations.CreateBookingJsonResponse> {
    return unwrapAsync(bookingPaymentBookingsCreateJson(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a booking
   *
   * @remarks
   * A booking is a temporary hold on a trip. It is not confirmed until the payment is processed.
   */
  async createRaw(
    request: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array,
    options?: RequestOptions & { acceptHeaderOverride?: CreateRawAcceptEnum },
  ): Promise<operations.CreateBookingRawResponse> {
    return unwrapAsync(bookingPaymentBookingsCreateRaw(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a booking
   *
   * @remarks
   * Returns the details of a specific booking.
   */
  async get(
    request: operations.GetBookingRequest,
    options?: RequestOptions & { acceptHeaderOverride?: GetAcceptEnum },
  ): Promise<operations.GetBookingResponse> {
    return unwrapAsync(bookingPaymentBookingsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a booking
   *
   * @remarks
   * Deletes a booking, cancelling the hold on the trip.
   */
  async delete(
    request: operations.DeleteBookingRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteBookingResponse | undefined> {
    return unwrapAsync(bookingPaymentBookingsDelete(
      this,
      request,
      options,
    ));
  }
}
