/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ListAcceptEnum, searchTripsList } from "../funcs/searchTripsList.js";
import {
  searchTripsSubscribeTrip,
  SubscribeTripAcceptEnum,
} from "../funcs/searchTripsSubscribeTrip.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export { ListAcceptEnum } from "../funcs/searchTripsList.js";

export { SubscribeTripAcceptEnum } from "../funcs/searchTripsSubscribeTrip.js";

export class Trips extends ClientSDK {
  /**
   * Get available train trips
   *
   * @remarks
   * Returns a list of available train trips between the specified origin and destination stations on the given date, and allows for filtering by bicycle and dog allowances.
   */
  async list(
    request: operations.GetTripsRequest,
    options?: RequestOptions & { acceptHeaderOverride?: ListAcceptEnum },
  ): Promise<operations.GetTripsResponse> {
    return unwrapAsync(searchTripsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Subscribe to live trip updates
   *
   * @remarks
   * Open a stream of live updates for a trip, such as delays, platform
   * changes, and departure or arrival events.
   *
   * Choose JSON Lines (`application/jsonl`) or Server-Sent Events
   * (`text/event-stream`) with the `Accept` header. The connection stays
   * open until the trip arrives, is cancelled, or the client disconnects.
   */
  async subscribeTrip(
    request: operations.SubscribeTripRequest,
    options?: RequestOptions & {
      acceptHeaderOverride?: SubscribeTripAcceptEnum;
    },
  ): Promise<operations.SubscribeTripResponse> {
    return unwrapAsync(searchTripsSubscribeTrip(
      this,
      request,
      options,
    ));
  }
}
