/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as b64$ from "../../lib/base64.js";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * A booking for a train trip.
 */
export type CreateBookingRawBookingsResponseBody = {
  /**
   * Unique identifier for the booking
   */
  id?: string | undefined;
  /**
   * Identifier of the booked trip
   */
  tripId?: string | undefined;
  /**
   * Name of the passenger
   */
  passengerName?: string | undefined;
  /**
   * Indicates whether the passenger has a bicycle.
   */
  hasBicycle?: boolean | undefined;
  /**
   * Indicates whether the passenger has a dog.
   */
  hasDog?: boolean | undefined;
  /**
   * The link to the current resource.
   */
  links?: components.LinksSelf | undefined;
};

/**
 * A booking for a train trip.
 */
export type CreateBookingRawResponseBody = {
  /**
   * Unique identifier for the booking
   */
  id?: string | undefined;
  /**
   * Identifier of the booked trip
   */
  tripId?: string | undefined;
  /**
   * Name of the passenger
   */
  passengerName?: string | undefined;
  /**
   * Indicates whether the passenger has a bicycle.
   */
  hasBicycle?: boolean | undefined;
  /**
   * Indicates whether the passenger has a dog.
   */
  hasDog?: boolean | undefined;
  /**
   * The link to the current resource.
   */
  links?: components.LinksSelf | undefined;
};

export type CreateBookingRawResponseResult =
  | CreateBookingRawResponseBody
  | Uint8Array
  | string;

export type CreateBookingRawResponse = {
  headers: { [k: string]: Array<string> };
  result: CreateBookingRawResponseBody | Uint8Array | string;
};

/** @internal */
export const CreateBookingRawBookingsResponseBody$inboundSchema: z.ZodType<
  CreateBookingRawBookingsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  trip_id: z.string().optional(),
  passenger_name: z.string().optional(),
  has_bicycle: z.boolean().optional(),
  has_dog: z.boolean().optional(),
  links: components.LinksSelf$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "trip_id": "tripId",
    "passenger_name": "passengerName",
    "has_bicycle": "hasBicycle",
    "has_dog": "hasDog",
  });
});

export function createBookingRawBookingsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingRawBookingsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateBookingRawBookingsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingRawBookingsResponseBody' from JSON`,
  );
}

/** @internal */
export const CreateBookingRawResponseBody$inboundSchema: z.ZodType<
  CreateBookingRawResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  trip_id: z.string().optional(),
  passenger_name: z.string().optional(),
  has_bicycle: z.boolean().optional(),
  has_dog: z.boolean().optional(),
  links: components.LinksSelf$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "trip_id": "tripId",
    "passenger_name": "passengerName",
    "has_bicycle": "hasBicycle",
    "has_dog": "hasDog",
  });
});

export function createBookingRawResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingRawResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBookingRawResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingRawResponseBody' from JSON`,
  );
}

/** @internal */
export const CreateBookingRawResponseResult$inboundSchema: z.ZodType<
  CreateBookingRawResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => CreateBookingRawResponseBody$inboundSchema),
  b64$.zodInbound,
]);

export function createBookingRawResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingRawResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBookingRawResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingRawResponseResult' from JSON`,
  );
}

/** @internal */
export const CreateBookingRawResponse$inboundSchema: z.ZodType<
  CreateBookingRawResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    z.lazy(() => CreateBookingRawResponseBody$inboundSchema),
    b64$.zodInbound,
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function createBookingRawResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingRawResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBookingRawResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingRawResponse' from JSON`,
  );
}
