/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as b64$ from "../../lib/base64.js";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * A booking for a train trip.
 */
export type CreateBookingJsonBookingsResponseBody = {
  /**
   * Unique identifier for the booking
   */
  id?: string | undefined;
  /**
   * Identifier of the booked trip
   */
  tripId?: string | undefined;
  /**
   * Name of the passenger
   */
  passengerName?: string | undefined;
  /**
   * Indicates whether the passenger has a bicycle.
   */
  hasBicycle?: boolean | undefined;
  /**
   * Indicates whether the passenger has a dog.
   */
  hasDog?: boolean | undefined;
  /**
   * The link to the current resource.
   */
  links?: components.LinksSelf | undefined;
};

/**
 * A booking for a train trip.
 */
export type CreateBookingJsonResponseBody = {
  /**
   * Unique identifier for the booking
   */
  id?: string | undefined;
  /**
   * Identifier of the booked trip
   */
  tripId?: string | undefined;
  /**
   * Name of the passenger
   */
  passengerName?: string | undefined;
  /**
   * Indicates whether the passenger has a bicycle.
   */
  hasBicycle?: boolean | undefined;
  /**
   * Indicates whether the passenger has a dog.
   */
  hasDog?: boolean | undefined;
  /**
   * The link to the current resource.
   */
  links?: components.LinksSelf | undefined;
};

export type CreateBookingJsonResponseResult =
  | CreateBookingJsonResponseBody
  | Uint8Array
  | string;

export type CreateBookingJsonResponse = {
  headers: { [k: string]: Array<string> };
  result: CreateBookingJsonResponseBody | Uint8Array | string;
};

/** @internal */
export const CreateBookingJsonBookingsResponseBody$inboundSchema: z.ZodType<
  CreateBookingJsonBookingsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  trip_id: z.string().optional(),
  passenger_name: z.string().optional(),
  has_bicycle: z.boolean().optional(),
  has_dog: z.boolean().optional(),
  links: components.LinksSelf$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "trip_id": "tripId",
    "passenger_name": "passengerName",
    "has_bicycle": "hasBicycle",
    "has_dog": "hasDog",
  });
});

export function createBookingJsonBookingsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingJsonBookingsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateBookingJsonBookingsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingJsonBookingsResponseBody' from JSON`,
  );
}

/** @internal */
export const CreateBookingJsonResponseBody$inboundSchema: z.ZodType<
  CreateBookingJsonResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  trip_id: z.string().optional(),
  passenger_name: z.string().optional(),
  has_bicycle: z.boolean().optional(),
  has_dog: z.boolean().optional(),
  links: components.LinksSelf$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "trip_id": "tripId",
    "passenger_name": "passengerName",
    "has_bicycle": "hasBicycle",
    "has_dog": "hasDog",
  });
});

export function createBookingJsonResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingJsonResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBookingJsonResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingJsonResponseBody' from JSON`,
  );
}

/** @internal */
export const CreateBookingJsonResponseResult$inboundSchema: z.ZodType<
  CreateBookingJsonResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => CreateBookingJsonResponseBody$inboundSchema),
  b64$.zodInbound,
]);

export function createBookingJsonResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingJsonResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBookingJsonResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingJsonResponseResult' from JSON`,
  );
}

/** @internal */
export const CreateBookingJsonResponse$inboundSchema: z.ZodType<
  CreateBookingJsonResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    z.lazy(() => CreateBookingJsonResponseBody$inboundSchema),
    b64$.zodInbound,
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function createBookingJsonResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingJsonResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBookingJsonResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingJsonResponse' from JSON`,
  );
}
