/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as b64$ from "../../lib/base64.js";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetBookingsRequest = {
  /**
   * The page number to return
   */
  page?: number | undefined;
  /**
   * The number of items to return per page
   */
  limit?: number | undefined;
};

/**
 * Links to the next and previous pages of a paginated response.
 */
export type GetBookingsBookingsLinks = {
  self?: string | undefined;
  next?: string | undefined;
  prev?: string | undefined;
};

/**
 * This is a generic request/response wrapper which contains both data and links which serve as hypermedia controls (HATEOAS).
 */
export type GetBookingsBookingsResponseBody = {
  data?: Array<components.Booking> | undefined;
  links?: GetBookingsBookingsLinks | undefined;
};

/**
 * Links to the next and previous pages of a paginated response.
 */
export type GetBookingsLinks = {
  self?: string | undefined;
  next?: string | undefined;
  prev?: string | undefined;
};

/**
 * This is a generic request/response wrapper which contains both data and links which serve as hypermedia controls (HATEOAS).
 */
export type GetBookingsResponseBody = {
  data?: Array<components.Booking> | undefined;
  links?: GetBookingsLinks | undefined;
};

export type GetBookingsResponseResult =
  | GetBookingsResponseBody
  | Uint8Array
  | string;

export type GetBookingsResponse = {
  headers: { [k: string]: Array<string> };
  result: GetBookingsResponseBody | Uint8Array | string;
};

/** @internal */
export type GetBookingsRequest$Outbound = {
  page: number;
  limit: number;
};

/** @internal */
export const GetBookingsRequest$outboundSchema: z.ZodType<
  GetBookingsRequest$Outbound,
  z.ZodTypeDef,
  GetBookingsRequest
> = z.object({
  page: z.number().int().default(1),
  limit: z.number().int().default(10),
});

export function getBookingsRequestToJSON(
  getBookingsRequest: GetBookingsRequest,
): string {
  return JSON.stringify(
    GetBookingsRequest$outboundSchema.parse(getBookingsRequest),
  );
}

/** @internal */
export const GetBookingsBookingsLinks$inboundSchema: z.ZodType<
  GetBookingsBookingsLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  self: z.string().optional(),
  next: z.string().optional(),
  prev: z.string().optional(),
});

export function getBookingsBookingsLinksFromJSON(
  jsonString: string,
): SafeParseResult<GetBookingsBookingsLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBookingsBookingsLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBookingsBookingsLinks' from JSON`,
  );
}

/** @internal */
export const GetBookingsBookingsResponseBody$inboundSchema: z.ZodType<
  GetBookingsBookingsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(components.Booking$inboundSchema).optional(),
  links: z.lazy(() => GetBookingsBookingsLinks$inboundSchema).optional(),
});

export function getBookingsBookingsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetBookingsBookingsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBookingsBookingsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBookingsBookingsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetBookingsLinks$inboundSchema: z.ZodType<
  GetBookingsLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  self: z.string().optional(),
  next: z.string().optional(),
  prev: z.string().optional(),
});

export function getBookingsLinksFromJSON(
  jsonString: string,
): SafeParseResult<GetBookingsLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBookingsLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBookingsLinks' from JSON`,
  );
}

/** @internal */
export const GetBookingsResponseBody$inboundSchema: z.ZodType<
  GetBookingsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(components.Booking$inboundSchema).optional(),
  links: z.lazy(() => GetBookingsLinks$inboundSchema).optional(),
});

export function getBookingsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetBookingsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBookingsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBookingsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetBookingsResponseResult$inboundSchema: z.ZodType<
  GetBookingsResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => GetBookingsResponseBody$inboundSchema),
  b64$.zodInbound,
]);

export function getBookingsResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<GetBookingsResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBookingsResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBookingsResponseResult' from JSON`,
  );
}

/** @internal */
export const GetBookingsResponse$inboundSchema: z.ZodType<
  GetBookingsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    z.lazy(() => GetBookingsResponseBody$inboundSchema),
    b64$.zodInbound,
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function getBookingsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetBookingsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBookingsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBookingsResponse' from JSON`,
  );
}
