/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as b64$ from "../../lib/base64.js";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetStationsRequest = {
  /**
   * The page number to return
   */
  page?: number | undefined;
  /**
   * The number of items to return per page
   */
  limit?: number | undefined;
  /**
   * The latitude and longitude of the user's location, to narrow down the search results to sites within a proximity of this location.
   *
   * @remarks
   */
  coordinates?: string | undefined;
  /**
   * A search term to filter the list of stations by name or address.
   *
   * @remarks
   */
  search?: string | undefined;
  /**
   * Filter stations by country code
   */
  country?: string | undefined;
};

/**
 * Links to the next and previous pages of a paginated response.
 */
export type GetStationsLinks = {
  self?: string | undefined;
  next?: string | undefined;
  prev?: string | undefined;
};

/**
 * This is a generic request/response wrapper which contains both data and links which serve as hypermedia controls (HATEOAS).
 */
export type GetStationsStationsResponseBody = {
  data?: Array<components.Station> | undefined;
  links?: GetStationsLinks | undefined;
};

/**
 * Links to the next and previous pages of a paginated response.
 */
export type Links = {
  self?: string | undefined;
  next?: string | undefined;
  prev?: string | undefined;
};

/**
 * This is a generic request/response wrapper which contains both data and links which serve as hypermedia controls (HATEOAS).
 */
export type GetStationsResponseBody = {
  data?: Array<components.Station> | undefined;
  links?: Links | undefined;
};

export type GetStationsResponseResult =
  | GetStationsResponseBody
  | Uint8Array
  | string;

export type GetStationsResponse = {
  headers: { [k: string]: Array<string> };
  result: GetStationsResponseBody | Uint8Array | string;
};

/** @internal */
export type GetStationsRequest$Outbound = {
  page: number;
  limit: number;
  coordinates?: string | undefined;
  search?: string | undefined;
  country?: string | undefined;
};

/** @internal */
export const GetStationsRequest$outboundSchema: z.ZodType<
  GetStationsRequest$Outbound,
  z.ZodTypeDef,
  GetStationsRequest
> = z.object({
  page: z.number().int().default(1),
  limit: z.number().int().default(10),
  coordinates: z.string().optional(),
  search: z.string().optional(),
  country: z.string().optional(),
});

export function getStationsRequestToJSON(
  getStationsRequest: GetStationsRequest,
): string {
  return JSON.stringify(
    GetStationsRequest$outboundSchema.parse(getStationsRequest),
  );
}

/** @internal */
export const GetStationsLinks$inboundSchema: z.ZodType<
  GetStationsLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  self: z.string().optional(),
  next: z.string().optional(),
  prev: z.string().optional(),
});

export function getStationsLinksFromJSON(
  jsonString: string,
): SafeParseResult<GetStationsLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStationsLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStationsLinks' from JSON`,
  );
}

/** @internal */
export const GetStationsStationsResponseBody$inboundSchema: z.ZodType<
  GetStationsStationsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(components.Station$inboundSchema).optional(),
  links: z.lazy(() => GetStationsLinks$inboundSchema).optional(),
});

export function getStationsStationsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetStationsStationsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStationsStationsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStationsStationsResponseBody' from JSON`,
  );
}

/** @internal */
export const Links$inboundSchema: z.ZodType<Links, z.ZodTypeDef, unknown> = z
  .object({
    self: z.string().optional(),
    next: z.string().optional(),
    prev: z.string().optional(),
  });

export function linksFromJSON(
  jsonString: string,
): SafeParseResult<Links, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Links$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Links' from JSON`,
  );
}

/** @internal */
export const GetStationsResponseBody$inboundSchema: z.ZodType<
  GetStationsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(components.Station$inboundSchema).optional(),
  links: z.lazy(() => Links$inboundSchema).optional(),
});

export function getStationsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetStationsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStationsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStationsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetStationsResponseResult$inboundSchema: z.ZodType<
  GetStationsResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => GetStationsResponseBody$inboundSchema),
  b64$.zodInbound,
]);

export function getStationsResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<GetStationsResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStationsResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStationsResponseResult' from JSON`,
  );
}

/** @internal */
export const GetStationsResponse$inboundSchema: z.ZodType<
  GetStationsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    z.lazy(() => GetStationsResponseBody$inboundSchema),
    b64$.zodInbound,
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function getStationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetStationsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStationsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStationsResponse' from JSON`,
  );
}
