/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as b64$ from "../../lib/base64.js";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetTripsRequest = {
  /**
   * The page number to return
   */
  page?: number | undefined;
  /**
   * The number of items to return per page
   */
  limit?: number | undefined;
  /**
   * The ID of the origin station
   */
  origin: string;
  /**
   * The ID of the destination station
   */
  destination: string;
  /**
   * The date and time of the trip in ISO 8601 format in origin station's timezone.
   */
  date: Date;
  /**
   * Only return trips where bicycles are known to be allowed
   */
  bicycles?: boolean | undefined;
  /**
   * Only return trips where dogs are known to be allowed
   */
  dogs?: boolean | undefined;
};

/**
 * Links to the next and previous pages of a paginated response.
 */
export type GetTripsTripsLinks = {
  self?: string | undefined;
  next?: string | undefined;
  prev?: string | undefined;
};

/**
 * This is a generic request/response wrapper which contains both data and links which serve as hypermedia controls (HATEOAS).
 */
export type GetTripsTripsResponseBody = {
  data?: Array<components.Trip> | undefined;
  links?: GetTripsTripsLinks | undefined;
};

/**
 * The link to the destination station resource.
 */
export type Data = {
  /**
   * Unique identifier for the trip
   */
  id?: string | undefined;
  /**
   * The starting station of the trip
   */
  origin?: string | undefined;
  /**
   * The destination station of the trip
   */
  destination?: string | undefined;
  /**
   * The date and time when the trip departs
   */
  departureTime?: Date | undefined;
  /**
   * The date and time when the trip arrives
   */
  arrivalTime?: Date | undefined;
  /**
   * The name of the operator of the trip
   */
  operator?: string | undefined;
  /**
   * The cost of the trip
   */
  price?: number | undefined;
  /**
   * Indicates whether bicycles are allowed on the trip
   */
  bicyclesAllowed?: boolean | undefined;
  /**
   * Indicates whether dogs are allowed on the trip
   */
  dogsAllowed?: boolean | undefined;
  self?: string | undefined;
};

/**
 * Links to the next and previous pages of a paginated response.
 */
export type GetTripsLinks = {
  self?: string | undefined;
  next?: string | undefined;
  prev?: string | undefined;
};

/**
 * This is a generic request/response wrapper which contains both data and links which serve as hypermedia controls (HATEOAS).
 */
export type GetTripsResponseBody = {
  data?: Array<Data> | undefined;
  links?: GetTripsLinks | undefined;
};

export type GetTripsResponseResult = GetTripsResponseBody | Uint8Array | string;

export type GetTripsResponse = {
  headers: { [k: string]: Array<string> };
  result: GetTripsResponseBody | Uint8Array | string;
};

/** @internal */
export type GetTripsRequest$Outbound = {
  page: number;
  limit: number;
  origin: string;
  destination: string;
  date: string;
  bicycles: boolean;
  dogs: boolean;
};

/** @internal */
export const GetTripsRequest$outboundSchema: z.ZodType<
  GetTripsRequest$Outbound,
  z.ZodTypeDef,
  GetTripsRequest
> = z.object({
  page: z.number().int().default(1),
  limit: z.number().int().default(10),
  origin: z.string(),
  destination: z.string(),
  date: z.date().transform(v => v.toISOString()),
  bicycles: z.boolean().default(false),
  dogs: z.boolean().default(false),
});

export function getTripsRequestToJSON(
  getTripsRequest: GetTripsRequest,
): string {
  return JSON.stringify(GetTripsRequest$outboundSchema.parse(getTripsRequest));
}

/** @internal */
export const GetTripsTripsLinks$inboundSchema: z.ZodType<
  GetTripsTripsLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  self: z.string().optional(),
  next: z.string().optional(),
  prev: z.string().optional(),
});

export function getTripsTripsLinksFromJSON(
  jsonString: string,
): SafeParseResult<GetTripsTripsLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTripsTripsLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTripsTripsLinks' from JSON`,
  );
}

/** @internal */
export const GetTripsTripsResponseBody$inboundSchema: z.ZodType<
  GetTripsTripsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(components.Trip$inboundSchema).optional(),
  links: z.lazy(() => GetTripsTripsLinks$inboundSchema).optional(),
});

export function getTripsTripsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetTripsTripsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTripsTripsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTripsTripsResponseBody' from JSON`,
  );
}

/** @internal */
export const Data$inboundSchema: z.ZodType<Data, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string().optional(),
    origin: z.string().optional(),
    destination: z.string().optional(),
    departure_time: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ).optional(),
    arrival_time: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ).optional(),
    operator: z.string().optional(),
    price: z.number().optional(),
    bicycles_allowed: z.boolean().optional(),
    dogs_allowed: z.boolean().optional(),
    self: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "departure_time": "departureTime",
      "arrival_time": "arrivalTime",
      "bicycles_allowed": "bicyclesAllowed",
      "dogs_allowed": "dogsAllowed",
    });
  });

export function dataFromJSON(
  jsonString: string,
): SafeParseResult<Data, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Data$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Data' from JSON`,
  );
}

/** @internal */
export const GetTripsLinks$inboundSchema: z.ZodType<
  GetTripsLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  self: z.string().optional(),
  next: z.string().optional(),
  prev: z.string().optional(),
});

export function getTripsLinksFromJSON(
  jsonString: string,
): SafeParseResult<GetTripsLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTripsLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTripsLinks' from JSON`,
  );
}

/** @internal */
export const GetTripsResponseBody$inboundSchema: z.ZodType<
  GetTripsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(z.lazy(() => Data$inboundSchema)).optional(),
  links: z.lazy(() => GetTripsLinks$inboundSchema).optional(),
});

export function getTripsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetTripsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTripsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTripsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetTripsResponseResult$inboundSchema: z.ZodType<
  GetTripsResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => GetTripsResponseBody$inboundSchema),
  b64$.zodInbound,
]);

export function getTripsResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<GetTripsResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTripsResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTripsResponseResult' from JSON`,
  );
}

/** @internal */
export const GetTripsResponse$inboundSchema: z.ZodType<
  GetTripsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    z.lazy(() => GetTripsResponseBody$inboundSchema),
    b64$.zodInbound,
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function getTripsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetTripsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTripsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTripsResponse' from JSON`,
  );
}
