/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as b64$ from "../../lib/base64.js";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type QueryStationsRequest = {
  /**
   * The page number to return
   */
  page?: number | undefined;
  /**
   * The number of items to return per page
   */
  limit?: number | undefined;
  stationQuery?: components.StationQuery | undefined;
};

/**
 * Links to the next and previous pages of a paginated response.
 */
export type QueryStationsStationsLinks = {
  self?: string | undefined;
  next?: string | undefined;
  prev?: string | undefined;
};

/**
 * This is a generic request/response wrapper which contains both data and links which serve as hypermedia controls (HATEOAS).
 */
export type QueryStationsStationsResponseBody = {
  data?: Array<components.Station> | undefined;
  links?: QueryStationsStationsLinks | undefined;
};

/**
 * Links to the next and previous pages of a paginated response.
 */
export type QueryStationsLinks = {
  self?: string | undefined;
  next?: string | undefined;
  prev?: string | undefined;
};

/**
 * This is a generic request/response wrapper which contains both data and links which serve as hypermedia controls (HATEOAS).
 */
export type QueryStationsResponseBody = {
  data?: Array<components.Station> | undefined;
  links?: QueryStationsLinks | undefined;
};

export type QueryStationsResponseResult =
  | QueryStationsResponseBody
  | Uint8Array
  | string;

export type QueryStationsResponse = {
  headers: { [k: string]: Array<string> };
  result: QueryStationsResponseBody | Uint8Array | string;
};

/** @internal */
export type QueryStationsRequest$Outbound = {
  page: number;
  limit: number;
  StationQuery?: components.StationQuery$Outbound | undefined;
};

/** @internal */
export const QueryStationsRequest$outboundSchema: z.ZodType<
  QueryStationsRequest$Outbound,
  z.ZodTypeDef,
  QueryStationsRequest
> = z.object({
  page: z.number().int().default(1),
  limit: z.number().int().default(10),
  stationQuery: components.StationQuery$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    stationQuery: "StationQuery",
  });
});

export function queryStationsRequestToJSON(
  queryStationsRequest: QueryStationsRequest,
): string {
  return JSON.stringify(
    QueryStationsRequest$outboundSchema.parse(queryStationsRequest),
  );
}

/** @internal */
export const QueryStationsStationsLinks$inboundSchema: z.ZodType<
  QueryStationsStationsLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  self: z.string().optional(),
  next: z.string().optional(),
  prev: z.string().optional(),
});

export function queryStationsStationsLinksFromJSON(
  jsonString: string,
): SafeParseResult<QueryStationsStationsLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryStationsStationsLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryStationsStationsLinks' from JSON`,
  );
}

/** @internal */
export const QueryStationsStationsResponseBody$inboundSchema: z.ZodType<
  QueryStationsStationsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(components.Station$inboundSchema).optional(),
  links: z.lazy(() => QueryStationsStationsLinks$inboundSchema).optional(),
});

export function queryStationsStationsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<QueryStationsStationsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryStationsStationsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryStationsStationsResponseBody' from JSON`,
  );
}

/** @internal */
export const QueryStationsLinks$inboundSchema: z.ZodType<
  QueryStationsLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  self: z.string().optional(),
  next: z.string().optional(),
  prev: z.string().optional(),
});

export function queryStationsLinksFromJSON(
  jsonString: string,
): SafeParseResult<QueryStationsLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryStationsLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryStationsLinks' from JSON`,
  );
}

/** @internal */
export const QueryStationsResponseBody$inboundSchema: z.ZodType<
  QueryStationsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(components.Station$inboundSchema).optional(),
  links: z.lazy(() => QueryStationsLinks$inboundSchema).optional(),
});

export function queryStationsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<QueryStationsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryStationsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryStationsResponseBody' from JSON`,
  );
}

/** @internal */
export const QueryStationsResponseResult$inboundSchema: z.ZodType<
  QueryStationsResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => QueryStationsResponseBody$inboundSchema),
  b64$.zodInbound,
]);

export function queryStationsResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<QueryStationsResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryStationsResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryStationsResponseResult' from JSON`,
  );
}

/** @internal */
export const QueryStationsResponse$inboundSchema: z.ZodType<
  QueryStationsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    z.lazy(() => QueryStationsResponseBody$inboundSchema),
    b64$.zodInbound,
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function queryStationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<QueryStationsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryStationsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryStationsResponse' from JSON`,
  );
}
