/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { EventStream } from "../../lib/event-streams.js";
import { JsonLStream } from "../../lib/jsonl.js";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SubscribeTripRequest = {
  /**
   * The ID of the trip to subscribe to.
   */
  id: string;
};

export type SubscribeTripData = {
  event: string;
  data: string;
};

/**
 * A stream of live trip status updates
 */
export type SubscribeTripResponseBody = {
  data?: SubscribeTripData | undefined;
  event?: string | undefined;
  id?: string | undefined;
  retry?: number | undefined;
};

export type SubscribeTripResponseResult =
  | JsonLStream<components.TripUpdate>
  | EventStream<SubscribeTripResponseBody>;

export type SubscribeTripResponse = {
  headers: { [k: string]: Array<string> };
  result:
    | JsonLStream<components.TripUpdate>
    | EventStream<SubscribeTripResponseBody>;
};

/** @internal */
export type SubscribeTripRequest$Outbound = {
  id: string;
};

/** @internal */
export const SubscribeTripRequest$outboundSchema: z.ZodType<
  SubscribeTripRequest$Outbound,
  z.ZodTypeDef,
  SubscribeTripRequest
> = z.object({
  id: z.string(),
});

export function subscribeTripRequestToJSON(
  subscribeTripRequest: SubscribeTripRequest,
): string {
  return JSON.stringify(
    SubscribeTripRequest$outboundSchema.parse(subscribeTripRequest),
  );
}

/** @internal */
export const SubscribeTripData$inboundSchema: z.ZodType<
  SubscribeTripData,
  z.ZodTypeDef,
  unknown
> = z.object({
  event: z.string(),
  data: z.string(),
});

export function subscribeTripDataFromJSON(
  jsonString: string,
): SafeParseResult<SubscribeTripData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SubscribeTripData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubscribeTripData' from JSON`,
  );
}

/** @internal */
export const SubscribeTripResponseBody$inboundSchema: z.ZodType<
  SubscribeTripResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.unknown().optional().transform((v, ctx) => {
    if (v === undefined) return undefined;
    if (typeof v !== "string") return v;
    try {
      return JSON.parse(v);
    } catch (err) {
      ctx.addIssue({ code: "custom", message: `malformed json: ${err}` });
      return z.NEVER;
    }
  }).pipe(z.lazy(() => SubscribeTripData$inboundSchema).optional()),
  event: z.string().optional(),
  id: z.string().optional(),
  retry: z.number().int().optional(),
});

export function subscribeTripResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<SubscribeTripResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SubscribeTripResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubscribeTripResponseBody' from JSON`,
  );
}

/** @internal */
export const SubscribeTripResponseResult$inboundSchema: z.ZodType<
  SubscribeTripResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.instanceof(ReadableStream<Uint8Array>).transform(stream => {
    return new JsonLStream({
      stream,
      decoder(rawEvent) {
        const schema = components.TripUpdate$inboundSchema;
        return schema.parse(rawEvent);
      },
    });
  }),
  z.instanceof(ReadableStream<Uint8Array>)
    .transform(stream => {
      return new EventStream(stream, rawEvent => {
        return {
          done: false,
          value: z.lazy(() => SubscribeTripResponseBody$inboundSchema).parse(
            rawEvent,
          ),
        };
      }, { dataRequired: false });
    }),
]);

export function subscribeTripResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<SubscribeTripResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SubscribeTripResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubscribeTripResponseResult' from JSON`,
  );
}

/** @internal */
export const SubscribeTripResponse$inboundSchema: z.ZodType<
  SubscribeTripResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    z.instanceof(ReadableStream<Uint8Array>).transform(stream => {
      return new JsonLStream({
        stream,
        decoder(rawEvent) {
          const schema = components.TripUpdate$inboundSchema;
          return schema.parse(rawEvent);
        },
      });
    }),
    z.instanceof(ReadableStream<Uint8Array>)
      .transform(stream => {
        return new EventStream(stream, rawEvent => {
          return {
            done: false,
            value: z.lazy(() => SubscribeTripResponseBody$inboundSchema).parse(
              rawEvent,
            ),
          };
        }, { dataRequired: false });
      }),
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function subscribeTripResponseFromJSON(
  jsonString: string,
): SafeParseResult<SubscribeTripResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SubscribeTripResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubscribeTripResponse' from JSON`,
  );
}
