/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * A booking for a train trip.
 */
export type Booking = {
  /**
   * Unique identifier for the booking
   */
  id?: string | undefined;
  /**
   * Identifier of the booked trip
   */
  tripId?: string | undefined;
  /**
   * Name of the passenger
   */
  passengerName?: string | undefined;
  /**
   * Indicates whether the passenger has a bicycle.
   */
  hasBicycle?: boolean | undefined;
  /**
   * Indicates whether the passenger has a dog.
   */
  hasDog?: boolean | undefined;
};

/** @internal */
export const Booking$inboundSchema: z.ZodType<Booking, z.ZodTypeDef, unknown> =
  z.object({
    id: z.string().optional(),
    trip_id: z.string().optional(),
    passenger_name: z.string().optional(),
    has_bicycle: z.boolean().optional(),
    has_dog: z.boolean().optional(),
  }).transform((v) => {
    return remap$(v, {
      "trip_id": "tripId",
      "passenger_name": "passengerName",
      "has_bicycle": "hasBicycle",
      "has_dog": "hasDog",
    });
  });

export function bookingFromJSON(
  jsonString: string,
): SafeParseResult<Booking, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Booking$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Booking' from JSON`,
  );
}
