/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * A train station.
 */
export type Station = {
  /**
   * Unique identifier for the station.
   */
  id: string;
  /**
   * The name of the station
   */
  name: string;
  /**
   * The address of the station.
   */
  address: string;
  /**
   * The country code of the station.
   */
  countryCode: string;
  /**
   * The timezone of the station in the [IANA Time Zone Database format](https://www.iana.org/time-zones).
   */
  timezone?: string | undefined;
};

/** @internal */
export const Station$inboundSchema: z.ZodType<Station, z.ZodTypeDef, unknown> =
  z.object({
    id: z.string(),
    name: z.string(),
    address: z.string(),
    country_code: z.string(),
    timezone: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "country_code": "countryCode",
    });
  });

export function stationFromJSON(
  jsonString: string,
): SafeParseResult<Station, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Station$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Station' from JSON`,
  );
}
