/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type StationQuery = {
  /**
   * The latitude and longitude of the user's location, to narrow down the search results to sites within a proximity of this location.
   */
  coordinates?: string | undefined;
  /**
   * A search term to filter the list of stations by name or address.
   */
  search?: string | undefined;
  /**
   * Filter stations by country code
   */
  country?: string | undefined;
};

/** @internal */
export type StationQuery$Outbound = {
  coordinates?: string | undefined;
  search?: string | undefined;
  country?: string | undefined;
};

/** @internal */
export const StationQuery$outboundSchema: z.ZodType<
  StationQuery$Outbound,
  z.ZodTypeDef,
  StationQuery
> = z.object({
  coordinates: z.string().optional(),
  search: z.string().optional(),
  country: z.string().optional(),
});

export function stationQueryToJSON(stationQuery: StationQuery): string {
  return JSON.stringify(StationQuery$outboundSchema.parse(stationQuery));
}
