/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The kind of update.
 */
export const Type = {
  Delay: "delay",
  Platform: "platform",
  Departed: "departed",
  Arrived: "arrived",
  Cancelled: "cancelled",
} as const;
/**
 * The kind of update.
 */
export type Type = ClosedEnum<typeof Type>;

/**
 * A live status update for a trip.
 */
export type TripUpdate = {
  /**
   * The kind of update.
   */
  type: Type;
  /**
   * Identifier of the trip this update belongs to.
   */
  tripId: string;
  /**
   * When the update occurred.
   */
  occurredAt: Date;
  /**
   * Delay in minutes. Present when `type` is `delay`.
   */
  minutes?: number | undefined;
  /**
   * Human-readable reason for the update.
   */
  reason?: string | undefined;
  /**
   * Assigned platform. Present when `type` is `platform`.
   */
  platform?: string | undefined;
};

/** @internal */
export const Type$inboundSchema: z.ZodNativeEnum<typeof Type> = z.nativeEnum(
  Type,
);

/** @internal */
export const TripUpdate$inboundSchema: z.ZodType<
  TripUpdate,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: Type$inboundSchema,
  trip_id: z.string(),
  occurred_at: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ),
  minutes: z.number().int().optional(),
  reason: z.string().optional(),
  platform: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "trip_id": "tripId",
    "occurred_at": "occurredAt",
  });
});

export function tripUpdateFromJSON(
  jsonString: string,
): SafeParseResult<TripUpdate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TripUpdate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TripUpdate' from JSON`,
  );
}
